### PR TITLE
Make viewer work better with HighDPI screens (pixelDensity)

### PR DESCRIPTION
**Pull request by maximaximal**
The pixelDensity(1) call was removed, so it is automatically computed by P5.js as described in https://p5js.org/reference/#/p5/pixelDensity

Now, text is as sharp on HighDPI screens as on regular ones. Otherwise, the text is (was) blurry. I looked a bit through the git history of your project but could not find a reason for the pixelDensity(1) call, as it works better without it. Maybe there was an issue with old P5.js versions? Works perfectly on my end now though.

I hope including a new screenshot is fine for this change, it also demonstrates how it looks without blurry text. My concern is that this may not pass some testing pipeline now, but that has to be seen on other setups... Interestingly, colors also look a bit more lively with the automatically computed pixel density.

### CODE REVIEW

**Comment by johnbeech** [comment]
Hey @maximaximal - thank you for the PR. I've reviewed the high resolution mode in-situ and am happy with how it looks.

What I am struggling with is matching the locally rendered screenshots with the sample - maybe I put pixelDensity(1) in to help with the testing; but in practice this is an unnecessary addition. My high res text looks very slightly different compared to your [default-map-expected.png](https://github.com/df-map-archive/dfma-html5-map-viewer/pull/37/files#diff-c9681a9961cfd895bf323405112002316e6b7de4a2960c8839f76f166d6f720d) - but that's ok.

At the moment; (when I wrote the integration test) I couldn't get them to work as part of the PR pipeline - so they're not super important - but it is a good way to check that the map viewer is working (i.e. decoding and rendering).

What I think I'll do is merge your change to release a new version, and then update the image to match my local rendering

**Review by johnbeech — APPROVED** [review]
Happy to merge; will prepare a new release to coincide with fixes in #35

**Comment by maximaximal** [comment]
Hey, very welcome! I'll happily contribute some more small things (interaction-related and for having multiple viewers on one page, maybe also performance related if I come around to it), it's a really nice project and a great idea to have a direct web-based viewer on the DFMA :)

Yes, I figured that the screenshot didn't work with the PR pipeline - but I'm glad you found a workaround with your local result.

**Comment by johnbeech** [comment]
@maximaximal - would be very happy for another person to get their head into the code base - if you can get it running locally, you can use the following URL format to test a local build of the viewer with real map data from the server:

- https://mkv25.net/dfma/map-7993-severedcoils?viewer=html5&version=localhost

Local build + run command:
```
npm run build && npm start
```

I'm currently tasked with hunting down general errors - but there's lots of quality of life improvements - keyboard shortcuts, onscreen buttons, dynamic resizing, efficient rendering, etc. 

The big one is trying to figure out how to render side views so that side orientation points of interest make sense again.

**Comment by maximaximal** [comment]
Nice, that helps. Thank you!

Yes, that's a quite a list of tasks already.

I don't have flash available anywhere - how did the side views look in the past? Did you just render the same sprites you render from above, just sideways and over multiple Z levels? That requires some refactoring of the current code I guess, but it should be doable.

**Comment by johnbeech** [comment]
Hey Max, I've opened https://github.com/df-map-archive/dfma-html5-map-viewer/issues/38 with a screenshot of the icons - side views basically took the individual tiles, from multiple layers, and rendered them as is (top down) onto side views - which are orientated in the database table as "top", "side", or "front". 

I've updated https://github.com/df-map-archive/dfma-html5-map-viewer/issues/12 with some more details of different types of Points of Interest and a linked example to a side view.

**Comment by maximaximal** [comment]
Perfect, thank you! Making more and more sense now. Let's see how this goes!

**Pull request merged**
